const strings = {
  payers: "¿Quiénes pagaron?",
  participants: "¿Cuántos más comparten?",
  new_payer: "Nombre",
  placeholder_name_hint: "Ej: Juan",
  placeholder_price_hint: "Monto que pagó",
  section_hint_payers: "Empezá agregando a quienes pagaron",
  section_hint_participants: "Sumá a los que no pagaron pero comparten",
  total: "Total",
  each_pays: "Cada uno paga",
  receives: "Le deben",
  owes: "Debe",
  should_pay_singular: "Debe pagarle",
  should_pay_plural: "Deben pagarle",
  people: "personas",
  person: "persona",
  share: "Compartir",
  new_split: "Nueva división",
  start: "Empezar",
  empty_title: "Dividí cuentas fácil",
  empty_subtitle: "Agregá quiénes pagaron y cuántos comparten el gasto",
  remainder: "Sobrante",
  copied: "Copiado al portapapeles",
  confirm_reset_title: "Nueva división",
  confirm_reset_message: "¿Estás seguro? Se borrarán todos los datos.",
  cancel: "Cancelar",
  confirm: "Confirmar",
  payment_flow_title: "¿Quién le paga a quién?",
};

export default strings;
